sudo: required

language: generic

services: 
  - docker

before_install:
  - echo "start creating image"
  - docker build -t jongin1004/docekr-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jongin1004/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"