sudo: required

language: generic

services: 
  - docker

before_install:
  - echo "test start creating image of docker"
  - docker build -t jongin1004/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jongin1004/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-543615709868"
  on:
    branch: master
